name: Build .NET Framework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    environment: DEV

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2
      
    - name: Restore NuGet packages
      run: nuget restore

    - name: Build
      run: msbuild /p:Configuration=Release

    - name: List files after build
      run: dir

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/aspnet-custom-font:${{ github.sha }} .
    
    # - name: Run Trivy vulnerability scanner
    #   uses: aquasecurity/trivy-action@0.28.0
    #   with:
    #     image-ref: '${{ secrets.ACR_LOGIN_SERVER }}/aspnet-custom-font:${{ github.sha }}'
    #     format: 'table'
    #     exit-code: '1'
    #     ignore-unfixed: true
    #     vuln-type: 'os,library'
    #     scanners: 'vuln'
    #     severity: 'CRITICAL,HIGH'
    #     timeout: 60m

    - name: Push Docker image
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/aspnet-custom-font:${{ github.sha }}